Repository WildCodeSchool-CDA-FT-2025-03/CDA-Projet-2-Team-1, pull requests merged in 2025-06, with the labels that each got.

#88 Pcp 151 en tant qu agent je veux rechercher les patients par ssn
  backend/appointment-service/src/resolvers/consultation.resolver.ts
  files/datatest/dataSetPatient.sql
  frontend/src/components/agent/ConsultationAgentDisplay.tsx
  frontend/src/components/agent/SsnSearchBar.tsx
  frontend/src/gql/graphql-types.ts
  frontend/src/pages/AgentPage.tsx
  frontend/src/schemas/consultation.schema.ts
  frontend/src/utiles/ssn.utility.ts
Labels: Review validé, Prêt à merge

#87 Pcp 203 front creer le formulaire d ajout d utilisateur
  files/datatest/dataset_authentification.sql
  frontend/src/components/formUi/Select.tsx
  frontend/src/components/role/RoleList.tsx
  frontend/src/components/service/ServiceList.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/user/AddUserForm.tsx
  frontend/src/index.css
  frontend/tailwind.config.js
Labels: Review validé, Prêt à merge

#82 Pcp 135 en tant qu utilisateur je dois pouvoir me connecter
  .eslintrc.js
  .gitignore
  backend/appointment-service/src/entities/patient.entity.ts
  backend/appointment-service/src/services/client.service.ts
  backend/auth-service/.env.sample
  backend/auth-service/.gitignore
  backend/auth-service/Dockerfile
  backend/auth-service/package-lock.json
  backend/auth-service/package.json
  backend/auth-service/src/controllers/loginController.ts
  backend/auth-service/src/database/config.ts
  backend/auth-service/src/index.ts
  backend/auth-service/src/middleware/VerifyKeys/validateLoginQuery.middleware.ts
  backend/auth-service/src/repository/testPoolConnection.config.repository.ts
  backend/auth-service/src/repository/user.repository.ts
  backend/auth-service/src/router/router.ts
  backend/auth-service/src/types/payloadTokenJWT.type.ts
  backend/auth-service/src/types/userTable.type.ts
  backend/auth-service/src/utils/Argon.utils.ts
  backend/auth-service/src/utils/createDateUtils.ts
  backend/auth-service/src/utils/jwtTokenCarePlan.utils.ts
  backend/auth-service/tsconfig.json
  docker-compose.dev.yml
  docs/doc.md
  files/.env-dev-default
  files/datatest/schema-express-login.sql
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.svg
  frontend/public/login.webp
  frontend/public/logo-cp-full.svg
  frontend/public/logo-cp.svg
  frontend/src/App.tsx
  frontend/src/components/LoginRoot/LoginRoot.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/context/Auth.context.tsx
  frontend/src/hook/.gitkeep
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/router/router.tsx
  frontend/src/types/DataUser.type.ts
  frontend/src/utils/validateFormLogin.ts
  lint-staged.config.js
Labels: Review en attente, Corrigé

#94 Pcp 148 en tant qu admin je veux ajouter un utilisateur
  backend/appointment-service/src/index.ts
  backend/appointment-service/src/resolvers/consultation.resolver.ts
  backend/appointment-service/src/resolvers/role.resolver.ts
  backend/appointment-service/src/resolvers/service.resolver.ts
  docker-compose.dev.yml
  files/datatest/dataset_authentification.sql
  frontend/src/components/formUi/Select.tsx
  frontend/src/components/role/RoleList.tsx
  frontend/src/components/service/ServiceList.tsx
  frontend/src/components/user/AddUserForm.tsx
  frontend/src/pages/AdminPage.tsx
  frontend/src/schemas/role.schema.ts
  frontend/src/schemas/service.schema.ts
  lint-staged.config.js
Labels: Review en attente

#101 Pcp 226 config GitHub action test eslint prettierrc
  .github/workflows/statics.yml
  .prettierignore
  frontend/commitlint.config.js
  frontend/components.json
  frontend/package.json
  frontend/playwright-report/index.html
  frontend/playwright.config.ts
  frontend/test-results/.last-run.json
  frontend/tests/home.spec.ts
Labels: Review validé, Prêt à merge

#99 Pcp 217 en tant que secretaire je veux pouvoir voir le detail une consultation
  backend/appointment-service/src/resolvers/consultation.resolver.ts
  files/datatest/dataSet_global.sql
  frontend/src/components/consultation/ConsultationDetails.tsx
  frontend/src/components/consultation/ConsultationList.tsx
  frontend/src/gql/graphql-types.ts
  frontend/src/router/router.tsx
  frontend/src/schemas/consultation.schema.ts
  frontend/src/utiles/date.utile.ts
Labels: Review en attente

#103 fix: docker-compose.test
  docker-compose.test.yml
Labels: Review en attente

#105 Pcp 232 fix fusion des dossiers utils et utiles
  frontend/src/components/LoginRoot/LoginRoot.tsx
  frontend/src/components/consultation/ConsultationDetails.tsx
  frontend/src/components/consultation/ConsultationList.tsx
  frontend/src/pages/AgentPage.tsx
  frontend/src/pages/SecretaryPage.tsx
  frontend/src/utils/date.utility.ts
  frontend/src/utils/ssn.utility.ts
  frontend/src/utils/validateFormLogin.utility.ts
Labels: Review en attente

#107 Pcp 234 fix déplacement des composants lies aux conges dans un dossier
  frontend/src/components/Modal.tsx
  frontend/src/components/RestModal.tsx
  frontend/src/components/rest/Rest.tsx
  frontend/src/components/rest/RestModal.tsx
  frontend/src/pages/DoctorPage.tsx
Labels: Review en attente

#108 hotfix: correction de l'import
  frontend/src/components/consultation/NoteSecretary.tsx
Labels: Review en attente

#109 Pcp 254 init microservice upload
  .github/workflows/statics.yml
  backend/upload-service/Dockerfile
  backend/upload-service/package-lock.json
  backend/upload-service/package.json
  backend/upload-service/src/index.ts
  backend/upload-service/src/router.ts
  backend/upload-service/tsconfig.json
  docker-compose.dev.yml
  files/.env-dev-default
  files/nginx.conf
Labels: Review en attente, Corrigé

#112 Pcp 231 en tant qu utilisateur je peux faire une demande d oublie de mot de passe afin de recevoir un email pour changer de mot de passe
  .prettierignore
  Makefile
  backend/auth-service/package-lock.json
  backend/auth-service/package.json
  backend/auth-service/src/controllers/resetController.ts
  backend/auth-service/src/repository/user.repository.ts
  backend/auth-service/src/router/router.ts
  backend/auth-service/src/schemas/reset.schema.ts
  backend/auth-service/src/services/email.service.ts
  backend/auth-service/src/types/payloadTokenJWT.type.ts
  backend/auth-service/src/utils/jwtTokenCarePlan.utils.ts
  backend/email-service/Dockerfile
  backend/email-service/jest.integration.config.ts
  backend/email-service/package-lock.json
  backend/email-service/package.json
  backend/email-service/src/controllers/reset.controller.ts
  backend/email-service/src/index.ts
  backend/email-service/src/middlewares/checkJWT.middleware.ts
  backend/email-service/src/middlewares/checkPayloadOrigin.middleware.ts
  backend/email-service/src/middlewares/errors.middleware.ts
  backend/email-service/src/router/router.ts
  backend/email-service/src/schemas/reset.schema.ts
  backend/email-service/src/services/logger.service.ts
  backend/email-service/src/services/mailer.service.ts
  backend/email-service/src/tests-integration/reset.test.ts
  backend/email-service/src/types/error.type.ts
  backend/email-service/src/types/payload.type.ts
  backend/email-service/src/utils/template.util.ts
  backend/email-service/src/views/reset.view.hbs
  backend/email-service/src/views/template.view.hbs
  backend/email-service/tsconfig.json
  docker-compose.dev.yml
  docker-compose.test.yml
  files/.env-dev-default
  files/nginx.conf
  frontend/src/components/LoginRoot/LoginRoot.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/user/RestPassword.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/router/router.tsx
Labels: Review en attente

#114 Pcp 240 en tant que secretaire je peux ajouter un ssn, nom et prenom du patient depuis ajouter un rdv
  backend/appointment-service/src/resolvers/patient.resolver.ts
  frontend/jest.config.cjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/consultation/CreateAppointmentDialog.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/gql/graphql-types.ts
  frontend/src/pages/SecretaryPage.tsx
  frontend/src/router/router.tsx
  frontend/src/schemas/patient.schema.ts
  frontend/tests-joi/CreateAppointmentDialog.joi.test.ts
  frontend/tsconfig.json
Labels: Corrigé, Review validé, Prêt à merge

#118 PCP-238 affichage services
  backend/appointment-service/src/entities/service.entity.ts
  backend/appointment-service/src/resolvers/service.resolver.ts
  frontend/src/components/consultation/CreateAppointmentDialog.tsx
  frontend/src/gql/graphql-types.ts
Labels: Corrigé

#116 Pcp 255 en tant que secretaire je peux ajouter un document depuis la fiche consultation
  Makefile
  backend/appointment-service/src/entities/consultation.entity.ts
  backend/appointment-service/src/entities/file.entity.ts
  backend/appointment-service/src/resolvers/file.resolver.ts
  backend/appointment-service/src/schemas/schemas.ts
  backend/appointment-service/src/services/client.service.ts
  backend/upload-service/src/controllers/file.controller.ts
  backend/upload-service/src/index.ts
  backend/upload-service/src/middlewares/multer.middleware.ts
  backend/upload-service/src/router.ts
  backend/upload-service/uploads/.gitkeep
  docker-compose.dev.yml
  files/datatest/dataSet_global.sql
  files/nginx.conf
  frontend/codegen.ts
  frontend/src/components/consultation/ConsultationDetails.tsx
  frontend/src/components/consultation/FileList.tsx
  frontend/src/components/consultation/UploadFile.tsx
  frontend/src/gql/graphql-types.ts
  frontend/src/schemas/file.schema.ts
  frontend/src/types/file.type.ts
Labels: Review validé, Prêt à merge

#121 fix: frontend target dev & jest config maxWorker=1
  backend/appointment-service/jest.integration.config.ts
  docker-compose.dev.yml
Labels: Review en attente, Review validé

#122 Pcp 262 mise en forme de la page secretaire
  frontend/src/App.tsx
  frontend/src/components/consultation/ConsultationList.tsx
  frontend/src/components/patients/PatientDialog.tsx
  frontend/src/index.css
  frontend/src/pages/AgentPage.tsx
  frontend/src/pages/SecretaryPage.tsx
Labels: Review en attente

#128 ajoute dataSet pour la demo
  files/datatest/dataSet_demo.sql
Labels: Review validé, Prêt à merge

#130 Pcp 267 fix demo
  backend/appointment-service/src/resolvers/user.resolver.ts
  files/datatest/dataSet_demo.sql
  frontend/src/components/Header.tsx
  frontend/src/components/patients/CreatePatient.tsx
  frontend/src/pages/SecretaryPage.tsx
Labels: Review en attente

#131 predeploy
  backend/appointment-service/src/entities/consultation-reason.entity.ts
  backend/appointment-service/src/entities/consultation.entity.ts
  backend/appointment-service/src/resolvers/consultation-reason.resolver.ts
  backend/appointment-service/src/resolvers/patient.resolver.ts
  backend/appointment-service/src/resolvers/user.resolver.ts
  backend/appointment-service/src/schemas/consultation-reason.schema.ts
  backend/appointment-service/src/schemas/schemas.ts
  backend/appointment-service/src/services/client.service.ts
  backend/auth-service/src/controllers/registersController.ts
  backend/auth-service/src/repository/user.repository.ts
  backend/auth-service/src/types/activationPayload.type.ts
  backend/auth-service/src/utils/jwtTokenCarePlan.utils.ts
  backend/email-service/src/controllers/accountActivation.controller.ts
  backend/email-service/src/router/router.ts
  backend/email-service/src/schemas/activation.schema.ts
  backend/email-service/src/types/activation.type.ts
  backend/email-service/src/views/activation.view.hbs
  files/datatest/dataSetPatient.sql
  files/datatest/dataSet_demo.sql
  files/datatest/ryan.sql
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/consultation/ConsultationList.tsx
  frontend/src/components/consultation/CreateAppointmentDialog.tsx
  frontend/src/components/patients/CreatePatient.tsx
  frontend/src/components/patients/PatientDetail.tsx
  frontend/src/components/patients/PatientDialog.tsx
  frontend/src/components/patients/PatientEditForm.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/calendar.tsx
  frontend/src/gql/graphql-types.ts
  frontend/src/index.css
  frontend/src/pages/AgentPage.tsx
  frontend/src/pages/SecretaryPage.tsx
  frontend/src/schemas/consultation-reason.schema.ts
  frontend/src/schemas/patient.schema.ts
  frontend/src/schemas/service.schema.ts
  frontend/src/types/patient.ts
  package-lock.json
Labels: Review validé, Prêt à merge

#133 feat: ajout duree de consultation
  frontend/src/components/consultation/CreateAppointmentDialog.tsx
Labels: Review en attente
