Repository WildCodeSchool-CDA-FT-2025-03/CDA-Projet-2-Team-1, pull requests merged in 2025-05, with the labels that each got.

#11 Pcp 70 initialisation du serveur express avec service fonctionnel
  backend/email-service/.env.base.sample
  backend/email-service/.env.development.sample
  backend/email-service/.env.production.sample
  backend/email-service/.gitignore
  backend/email-service/package-lock.json
  backend/email-service/package.json
  backend/email-service/src/config/CorsOrigins.config.ts
  backend/email-service/src/config/ENV.config.ts
  backend/email-service/src/config/dotenv.config.ts
  backend/email-service/src/controllers/registerController.ts
  backend/email-service/src/database/config.ts
  backend/email-service/src/index.ts
  backend/email-service/src/middleware/.gitkeep
  backend/email-service/src/middleware/VerifyKeys/VerifyKeys.ts
  backend/email-service/src/repository/emailRepository.ts
  backend/email-service/src/repository/insertUserRepository.ts
  backend/email-service/src/router/router.ts
  backend/email-service/src/security/LimiteRequestIP.ts
  backend/email-service/src/security/middlewareSecurity/RouteLimiterRequestIP.ts
  backend/email-service/src/services/mailer.ts
  backend/email-service/src/services/sendMailerService.ts
  backend/email-service/src/types/dataUserType.ts
  backend/email-service/src/types/environnement.config.type.ts
  backend/email-service/src/types/mailOptionsType.ts
  backend/email-service/src/types/payloadType.ts
  backend/email-service/src/utils/hashArgonUtils.ts
  backend/email-service/tsconfig.json
Labels: Review validé, Prêt à merge

#13 Pcp 70 initialisation du serveur express avec service fonctionnel login
  backend/email-service/package.json
  backend/email-service/src/controllers/loginController.ts
  backend/email-service/src/router/router.ts
  backend/email-service/src/utils/createDateUtils.ts
  backend/email-service/src/utils/jwtTokenCarePlanUtils.ts
  package.json
Labels: Review validé

#10 Pcp 44 creation de la page login
  backend/email-service/tsconfig.json
  frontend/components.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/imagelogin.svg
  frontend/public/logoText.svg
  frontend/src/App.tsx
  frontend/src/components/Login.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/index.css
  frontend/src/lib/button-variants.ts
  frontend/src/lib/utils.ts
  frontend/src/main.tsx
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/vite.config.ts
  package.json
Labels: Corrigé, Review validé, Prêt à merge

#14 Pcp 70 initialisation du serveur express avec service fonctionnel reset password
  backend/email-service/src/controllers/loginController.ts
  backend/email-service/src/controllers/resetPasswordController.ts
  backend/email-service/src/repository/insertTokenResetRepository.ts
  backend/email-service/src/repository/resetTokenRegulator.ts
  backend/email-service/src/router/router.ts
  backend/email-service/src/services/mailer.ts
  backend/email-service/src/services/sendMailerService.ts
  backend/email-service/src/utils/cryptoUtils.ts
  backend/email-service/src/utils/jwtTokenCarePlanUtils.ts
Labels: Review validé, Prêt à merge

#16 Fix@init
  .eslintrc.js
  frontend/.env
  frontend/.gitignore
  frontend/eslint.config.js
  frontend/package-lock.json
  frontend/package.json
  lint-staged.config.js
  package-lock.json
  package.json
Labels: Review en attente

#15 fix: packages
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/header/logocp.svg
Labels: Review validé, Prêt à merge

#18 Pcp 73 login page to router
  frontend/src/main.tsx
  frontend/src/pages/Login.tsx
  frontend/src/router/router.tsx
  package-lock.json
  package.json
Labels: Review en attente

#21 Pcp 71 back init appointment service
  Makefile
  backend/appointment-service/Dockerfile
  backend/appointment-service/package-lock.json
  backend/appointment-service/package.json
  backend/appointment-service/src/entities/patient.entity.ts
  backend/appointment-service/src/index.ts
  backend/appointment-service/src/resolvers/patient.resolver.ts
  backend/appointment-service/src/services/client.service.ts
  backend/appointment-service/src/services/logger.service.ts
  backend/appointment-service/tsconfig.json
  docker-compose.dev.yml
  files/.env-dev-default
Labels: Review en attente, Review validé

#23 Pcp 75 refactoriser import img
  frontend/public/favicon.svg
  frontend/public/imagelogin.svg
  frontend/public/login.webp
  frontend/public/logo-cp-full.svg
  frontend/public/logo-cp.svg
  frontend/public/logoText.svg
  frontend/src/components/header/header.tsx
  frontend/src/components/header/logocp.svg
  frontend/src/pages/Login.tsx
Labels: Review en attente

#27 Pcp 40 back creation entity service
  backend/appointment-service/src/entities/service.entity.ts
  backend/appointment-service/src/services/client.service.ts
Labels: Review en attente

#26 Pcp 33 back user entity
  .eslintrc.js
  backend/.eslintrc.js
  backend/appointment-service/src/entities/user.entity.ts
  backend/appointment-service/src/index.ts
  backend/appointment-service/src/resolvers/user.resolver.ts
  backend/appointment-service/src/services/client.service.ts
  lint-staged.config.js
  package-lock.json
  package.json
Labels: Review validé, Prêt à merge

#28 feat: entity ssn
  backend/appointment-service/src/entities/ssn.entity.ts
  backend/appointment-service/src/services/client.service.ts
Labels: Corrigé, Review validé, Prêt à merge

#32 fix: resolution des erreur d'import et package
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ui/calendar.tsx
  frontend/src/pages/SecretaryPage.tsx
Labels: Review en attente

#33 Pcp 78 front in docker compose
  Makefile
  docker-compose.dev.yml
  files/.env-dev-default
  frontend/Dockerfile
  frontend/vite.config.ts
Labels: Review en attente, Review validé

#31 Pcp 36 back creation entity city
  backend/appointment-service/src/entities/city.entity.ts
  backend/appointment-service/src/services/client.service.ts
Labels: Corrigé, Review validé

#35 Pcp 70 initialisation du serveur express avec service fonctionnel reset password confirm
  backend/email-service/src/controllers/resetPasswordConfirmController.ts
  backend/email-service/src/repository/getUserRepository.ts
  backend/email-service/src/repository/updateNewPasswordUserRepository.ts
  backend/email-service/src/router/router.ts
Labels: Corrigé, Review validé, Prêt à merge

#36 Pcp 37 back entity consultation
  backend/appointment-service/src/entities/consultation.entity.ts
  backend/appointment-service/src/index.ts
  backend/appointment-service/src/resolvers/consultation.resolver.ts
  backend/appointment-service/src/services/client.service.ts
Labels: Review validé, Prêt à merge

#37 Pcp 39 back creation entity consultation note rdv
  backend/appointment-service/src/entities/note_rdv.entity.ts
  backend/appointment-service/src/services/client.service.ts
Labels: Corrigé, Review validé

#39 feat:patient entity update
  backend/appointment-service/src/entities/patient.entity.ts
Labels: Corrigé, Review validé

#38 Pcp 38 back entity consultation motif
  backend/appointment-service/src/entities/consultation.entity.ts
  backend/appointment-service/src/entities/consultation_motif.entity.ts
  backend/appointment-service/src/entities/user.entity.ts
  backend/appointment-service/src/services/client.service.ts
Labels: Review en attente, Corrigé

#40 Pcp 81 back entity note secret
  backend/appointment-service/src/entities/consultation.entity.ts
  backend/appointment-service/src/entities/note_secret.entity.ts
  backend/appointment-service/src/index.ts
  backend/appointment-service/src/resolvers/note_secret.resolver.ts
  backend/appointment-service/src/services/client.service.ts
Labels: Review validé, Prêt à merge

#34 feat: add list of patient rdv
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/header/header.tsx
  frontend/src/components/ui/avatar.tsx
  frontend/src/components/ui/badge.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/calendar.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/scroll-area.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/data/patients.json
  frontend/src/pages/SecretaryPage.tsx
Labels: Corrigé, Review validé, Prêt à merge

#42 Pcp 79 back creation des relations
  backend/appointment-service/src/entities/city.entity.ts
  backend/appointment-service/src/entities/consultation.entity.ts
  backend/appointment-service/src/entities/file.entity.ts
  backend/appointment-service/src/entities/note_rdv.entity.ts
  backend/appointment-service/src/entities/note_secret.entity.ts
  backend/appointment-service/src/entities/patient.entity.ts
  backend/appointment-service/src/entities/role.entity.ts
  backend/appointment-service/src/entities/service.entity.ts
  backend/appointment-service/src/entities/ssn.entity.ts
  backend/appointment-service/src/entities/user.entity.ts
Labels: Review en attente, Corrigé, Review validé

#45 Pcp 87 back update tables et relations
  backend/appointment-service/src/entities/consultation.entity.ts
  backend/appointment-service/src/entities/file.entity.ts
  backend/appointment-service/src/entities/note_confidential.entity.ts
  backend/appointment-service/src/entities/note_secretary.entity.ts
  backend/appointment-service/src/entities/patient.entity.ts
  backend/appointment-service/src/entities/reason_consultation.entity.ts
  backend/appointment-service/src/entities/role.entity.ts
  backend/appointment-service/src/entities/service.entity.ts
  backend/appointment-service/src/entities/ssn.entity.ts
  backend/appointment-service/src/entities/user.entity.ts
  backend/appointment-service/src/index.ts
  backend/appointment-service/src/resolvers/consultation.resolver.ts
  backend/appointment-service/src/resolvers/note_secret.resolver.ts
  backend/appointment-service/src/resolvers/patient.resolver.ts
  backend/appointment-service/src/resolvers/user.resolver.ts
  backend/appointment-service/src/services/client.service.ts
Labels: Review en attente, Corrigé

#51 chore: init appointment-service
  backend/.eslintrc.js
  backend/appointment-service/.env.sample
  backend/appointment-service/Dockerfile
  backend/appointment-service/package-lock.json
  backend/appointment-service/package.json
  backend/appointment-service/src/entities/user.entity.ts
  backend/appointment-service/src/index.ts
  backend/appointment-service/src/resolvers/user.resolver.ts
  backend/appointment-service/src/services/client.service.ts
  backend/appointment-service/src/services/logger.service.ts
  backend/appointment-service/tsconfig.json
Labels: Review validé, Prêt à merge

#52 Ajout du concurrently
  frontend/.env.base.sample
  frontend/.env.development.sample
  frontend/.env.production.sample
  frontend/.gitignore
  frontend/vite.config.ts
  package-lock.json
  package.json
Labels: Review en attente

#53 Pcp 158 init root project make docker
  Makefile
  docker-compose.dev.yml
  files/.env-dev-default
  frontend/Dockerfile
Labels: Review validé, Prêt à merge

#57 dossier docs
  docs/doc.md
Labels: Review validé, Prêt à merge

#61 Fix@eslint prettier
  .eslintrc.js
  frontend/.prettierrc
  frontend/package.json
  frontend/vite.config.ts
  lint-staged.config.js
  package-lock.json
  package.json
Labels: Review en attente

#65 Pcp 178 back rework rest
  backend/appointment-service/src/entities/rest.entity.ts
  backend/appointment-service/src/entities/user.entity.ts
  backend/appointment-service/src/resolvers/rest.resolver.ts
  files/datatest/rest.sql
Labels: Corrigé, Review validé, Prêt à merge

#66 feature: calendrier rest dynamique avec l'id du médecin
  frontend/src/components/Rest.tsx
  frontend/src/pages/DoctorPage.tsx
  frontend/src/types/rest.type.ts
Labels: Review en attente

#68 Pcp 177 front shema codegen
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Rest.tsx
  frontend/src/gql/graphql-types.ts
  frontend/src/lib/apollo-client.ts
  frontend/src/main.tsx
  frontend/src/pages/DoctorPage.tsx
  frontend/src/schemas/rest.schema.ts
  frontend/src/types/rest.type.ts
Labels: Review validé, Prêt à merge

#70 Pcp 185 fix codegen package
  docs/doc.md
  frontend/package-lock.json
  frontend/src/components/Rest.tsx
  frontend/src/gql/graphql-types.ts
  package-lock.json
Labels: Corrigé, Review validé, Prêt à merge

#75 Pcp 136 en tant que medecin je veux poser mes conges
  backend/appointment-service/src/index.ts
  backend/appointment-service/src/resolvers/rest.resolver.ts
  frontend/codegen.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Rest.tsx
  frontend/src/components/RestModal.tsx
  frontend/src/gql/graphql-types.ts
  frontend/src/index.css
  frontend/src/schemas/rest.schema.ts
  frontend/src/types/rest.types.ts
  frontend/tailwind.config.js
Labels: Review en attente

#77 fix: modification de codegen et update de graphql-types
  frontend/src/gql/graphql-types.ts
Labels: Review en attente

#73 Pcp 186 en tant qu admin je peux consulter les rôles
  backend/appointment-service/src/entities/role.entity.ts
  backend/appointment-service/src/index.ts
  backend/appointment-service/src/resolvers/role.resolver.ts
  backend/appointment-service/src/services/client.service.ts
  files/datatest/dataset_authentification.sql
  frontend/codegen.ts
  frontend/src/components/formUi/Select.tsx
  frontend/src/components/role/RoleList.tsx
  frontend/src/components/user/AddUserForm.tsx
  frontend/src/gql/graphql-types.ts
  frontend/src/pages/AdminPage.tsx
  frontend/src/schemas/role.schema.ts
  lint-staged.config.js
Labels: Corrigé, Review validé

#86 Pcp 208 fix codegen
  backend/appointment-service/src/entities/user.entity.ts
  files/datatest/consultation.sql
  files/datatest/dataSetPatient.sql
  frontend/src/components/consultation/ConsultationList.tsx
  frontend/src/gql/graphql-types.ts
  frontend/src/schemas/consultation.schema.ts
Labels: Review en attente
